import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import * as C from '../challenge.js'

// Cross-language drift check for the passkey-PRF challenges.
//
// Source of truth: `fixtures/passkey_prf/v1/challenge_vectors.json`,
// generated by `fixtures/passkey_prf/v1/gen.ts`. The same JSON is consumed
// by the Rust SBF tests in `contracts/sbf-tests/tests/passkey_challenge_fixtures.rs`,
// so any byte drift across Rust ↔ TypeScript fails CI in both places.
//
// To intentionally change the wire format: edit `gen.ts`, run `npm run gen`
// in that fixtures directory, AND update `contracts/auth/src/challenge.rs`
// + `human_message.rs` in the SAME commit.

interface PasskeyFixtureFile {
  version: 'v1'
  program_id_bs58: string
  domain: string
  op_session_open: string
  op_primary_use: string
  inputs: {
    dwallet: string
    init_authority_hash: string
    credential_pubkey: string
    credential_id: string
    credential_id_hash: string
    primary_slot: string
    rp_id: string
    rp_origin: string
    eph_pk: string
    not_after_unix_ts: string
    session_nonce: string
    use_nonce: string
    signature_scheme: number
    message_approval_bump: number
    message_approval: string
    message_digest: string
    metadata_digest: string
    user_pubkey: string
  }
  pdas: {
    policy: { hex: string; base58: string }
    session: { hex: string; base58: string }
  }
  webauthn: {
    auth_data_hex: string
    auth_data_len: number
    client_data_json: string
    client_data_json_len: number
  }
  challenges: {
    open: { human_message: string; challenge_hex: string }
    use: { human_message: string; challenge_hex: string; eph_signature_hex: string; eph_signature_bad_hex: string }
  }
  salt: { strategy: 'per_credential'; salt_id: string; salt_hash: string }
}

const __dirname = dirname(fileURLToPath(import.meta.url))
// __tests__ → recovery → src → ika-backend → repo root → fixtures
const fixture = JSON.parse(
  readFileSync(
    join(__dirname, '../../../../fixtures/passkey_prf/v1/challenge_vectors.json'),
    'utf8',
  ),
) as PasskeyFixtureFile

const unhex = (s: string): Uint8Array => new Uint8Array(Buffer.from(s, 'hex'))
const hex = (u: Uint8Array): string => Buffer.from(u).toString('hex')
const I = fixture.inputs

describe('recovery/challenge — passkey-PRF golden vectors (must match contracts/auth/src/challenge.rs)', () => {
  it('domain + ops match the Rust constants', () => {
    expect(fixture.domain).toBe('andromeda::rules-policy::v2')
    expect(fixture.op_session_open).toBe('passkey-session-open')
    expect(fixture.op_primary_use).toBe('passkey-primary-use')
  })

  it('passkey_session_open challenge hashes to the frozen value', () => {
    const result = C.passkeySessionOpenChallenge({
      dwallet: unhex(I.dwallet),
      primarySlot: unhex(I.primary_slot),
      ephPk: unhex(I.eph_pk),
      notAfterUnixTs: BigInt(I.not_after_unix_ts),
      credentialIdHash: unhex(I.credential_id_hash),
      sessionNonce: BigInt(I.session_nonce),
    })
    expect(hex(result.hash)).toBe(fixture.challenges.open.challenge_hex)
    expect(result.humanMessage).toBe(fixture.challenges.open.human_message)
  })

  it('passkey_primary_use challenge hashes to the frozen value', () => {
    const result = C.passkeyPrimaryUseChallenge({
      session: unhex(fixture.pdas.session.hex),
      dwallet: unhex(I.dwallet),
      messageApproval: unhex(I.message_approval),
      messageDigest: unhex(I.message_digest),
      metadataDigest: unhex(I.metadata_digest),
      userPubkey: unhex(I.user_pubkey),
      signatureScheme: I.signature_scheme,
      messageApprovalBump: I.message_approval_bump,
      useNonce: BigInt(I.use_nonce),
      primarySlot: unhex(I.primary_slot),
    })
    expect(hex(result.hash)).toBe(fixture.challenges.use.challenge_hex)
    expect(result.humanMessage).toBe(fixture.challenges.use.human_message)
  })

  it('webauthn payload stays within the on-chain bounds (D13)', () => {
    expect(fixture.webauthn.auth_data_len).toBeLessThanOrEqual(192)
    expect(fixture.webauthn.client_data_json_len).toBeLessThanOrEqual(192)
    expect(fixture.webauthn.client_data_json).toContain('"challenge":"')
  })

  it('primary_slot is [SCHEME_WEBAUTHN(3), credential_pubkey(33)]', () => {
    const slot = unhex(I.primary_slot)
    expect(slot.length).toBe(34)
    expect(slot[0]).toBe(3)
    expect(hex(slot.slice(1, 34))).toBe(I.credential_pubkey)
  })

  it('credential_id_hash == sha256(credential_id) — D12 invariant', () => {
    const expectedHash = Buffer.from(
      require('node:crypto').createHash('sha256').update(unhex(I.credential_id)).digest(),
    ).toString('hex')
    expect(I.credential_id_hash).toBe(expectedHash)
  })
})
