//! Andromeda — Session Keys policy template.
//!
//! Lets the dWallet owner delegate signing authority to a temporary keypair
//! ("session key") under hard on-chain constraints:
//!   - expires_at_slot — automatic cutoff
//!   - max_uses        — total signatures the session can authorize
//!   - allowed_program_ids — caller (parsed_destination) whitelist
//!   - max_amount_per_tx   — per-tx amount cap
//!
//! Custody-free: Andromeda never holds the session keypair — the dev's app
//! generates and stores it client-side; this program registers the pubkey
//! and constraints on-chain so the Ika dWallet only signs when the session
//! keypair signs *first*.
//!
//! v2 (2026-05-07): owner is now wallet-agnostic and gas-sponsored. All
//! admin actions (`create_session`, `revoke_session`, `add_allowed_program`,
//! `remove_allowed_program`, `close_session`) authorize the owner via a
//! 32-byte off-chain challenge validated by `andromeda_auth`. The session
//! keypair still signs `request_signature_via_session` natively as a Solana
//! signer — that's the whole point of session keys.

#![no_std]
#![allow(dead_code)]

pub mod challenges;

use andromeda_auth::admin::verify_owner_admin;
use andromeda_auth::hash::hashv;
use andromeda_auth::human_message::HumanMessageError;
use andromeda_auth::precompile::check_sysvar_address;
use andromeda_auth::{
    validate_slot, verify_signature, AuthError, VerifyInput, MEMBER_SLOT_LEN, SCHEME_WEBAUTHN,
};
use andromeda_policy_shared::validate_ika_cpi_accounts;
use ika_dwallet_quasar::DWalletContext;
use quasar_lang::prelude::*;
use solana_address::Address;

declare_id!("3Y2QaXiJH3aSiooDnGQsZQhYN72r47mYYbHp9YWyiASm");

const MAX_ALLOWED_PROGRAMS: usize = 8;

#[program]
mod session_keys {
    use super::*;

    /// 0 — owner creates a session bound to a temporary keypair.
    ///
    /// Audit C2 fix (Opção 4): `init_authority_slot` is a wallet credential
    /// signing the canonical init challenge.
    /// Audit H6 fix: `session_index: u32` is part of the PDA seed, so a
    /// single dwallet+init_authority pair can have many sessions in flight.
    /// Audit C1 fix: `current_ts` from `Clock` sysvar.
    #[instruction(discriminator = 0)]
    #[allow(clippy::too_many_arguments)]
    pub fn create_session(
        ctx: Ctx<CreateSession>,
        init_authority_slot: [u8; MEMBER_SLOT_LEN],
        init_authority_hash: Address,
        session_index: u32,
        owner_slot: [u8; MEMBER_SLOT_LEN],
        session_key: Address,
        expires_at_slot: u64,
        max_amount_per_tx: u64,
        max_uses: u32,
    ) -> Result<(), ProgramError> {
        let current_ts: i64 = ctx.accounts.clock.unix_timestamp.into();
        let policy_addr = *ctx.accounts.session.address();
        let dwallet_addr = *ctx.accounts.dwallet_account.address();
        ctx.accounts.create(
            init_authority_slot,
            init_authority_hash,
            session_index,
            owner_slot,
            session_key,
            expires_at_slot,
            max_amount_per_tx,
            max_uses,
        )?;
        ctx.accounts.program.emit_event(
            &PolicyDeployed {
                policy: policy_addr,
                dwallet: dwallet_addr,
                ts: current_ts,
            },
            &ctx.accounts.event_authority,
            EventAuthority::BUMP,
        )?;
        Ok(())
    }

    /// 1 — session keypair signs a request; CPIs Ika::approve_message.
    /// `session_signer` is the temporary keypair generated by the dev's app —
    /// it's a Solana signer here (not the user's wallet).
    ///
    /// Audit C2 (Opção 4) + H6: `init_authority_hash` and `session_index`
    /// passed for PDA derivation.
    /// Audit C1 fix: `current_slot` and `current_ts` from `Clock` sysvar —
    /// fixes the expiry bypass where a manipulated slot could either kill an
    /// active session or revive an expired one.
    /// Audit H3 fix: `expected_signature_nonce` is consumed atomically per
    /// request, so a leaked session_key can produce at most one signature
    /// per nonce slot — replay across blockhash windows is blocked.
    #[instruction(discriminator = 1)]
    #[allow(clippy::too_many_arguments)]
    pub fn request_signature_via_session(
        ctx: Ctx<RequestSignatureViaSession>,
        _init_authority_hash: Address,
        _session_index: u32,
        message_digest: [u8; 32],
        metadata_digest: [u8; 32],
        user_pubkey: [u8; 32],
        signature_scheme: u16,
        message_approval_bump: u8,
        cpi_authority_bump: u8,
        amount: u64,
        destination_program: Address,
        expected_signature_nonce: u64,
    ) -> Result<(), ProgramError> {
        let current_slot: u64 = ctx.accounts.clock.slot.into();
        let current_ts: i64 = ctx.accounts.clock.unix_timestamp.into();
        let policy_addr = *ctx.accounts.session.address();
        let request_hash = Address::from(message_digest);
        ctx.accounts.program.emit_event(
            &SignatureRequested {
                policy: policy_addr,
                request_hash,
                ts: current_ts,
            },
            &ctx.accounts.event_authority,
            EventAuthority::BUMP,
        )?;
        ctx.accounts.request(
            message_digest,
            metadata_digest,
            user_pubkey,
            signature_scheme,
            message_approval_bump,
            cpi_authority_bump,
            amount,
            destination_program,
            current_slot,
            expected_signature_nonce,
        )?;
        ctx.accounts.program.emit_event(
            &SignatureApproved {
                policy: policy_addr,
                request_hash,
                ts: current_ts,
            },
            &ctx.accounts.event_authority,
            EventAuthority::BUMP,
        )?;
        Ok(())
    }

    /// 2 — owner force-expires the session (revoke_session_challenge).
    /// Audit C2 (Opção 4) + H6 + C1.
    #[instruction(discriminator = 2)]
    pub fn revoke_session(
        ctx: Ctx<AdminAction>,
        _init_authority_hash: Address,
        _session_index: u32,
        expected_nonce: u64,
    ) -> Result<(), ProgramError> {
        let current_ts: i64 = ctx.accounts.clock.unix_timestamp.into();
        let policy_addr = *ctx.accounts.session.address();
        ctx.accounts.revoke(expected_nonce)?;
        ctx.accounts.program.emit_event(
            &PolicyPaused {
                policy: policy_addr,
                ts: current_ts,
            },
            &ctx.accounts.event_authority,
            EventAuthority::BUMP,
        )?;
        Ok(())
    }

    /// 3 — owner appends a program to the allow-list. Idempotent.
    /// Audit C2 (Opção 4) + H6.
    #[instruction(discriminator = 3)]
    pub fn add_allowed_program(
        ctx: Ctx<AdminAction>,
        _init_authority_hash: Address,
        _session_index: u32,
        program_id: Address,
        expected_nonce: u64,
    ) -> Result<(), ProgramError> {
        ctx.accounts.add_program(program_id, expected_nonce)
    }

    /// 4 — owner removes a program from the allow-list. Idempotent.
    /// Audit C2 (Opção 4) + H6.
    #[instruction(discriminator = 4)]
    pub fn remove_allowed_program(
        ctx: Ctx<AdminAction>,
        _init_authority_hash: Address,
        _session_index: u32,
        program_id: Address,
        expected_nonce: u64,
    ) -> Result<(), ProgramError> {
        ctx.accounts.remove_program(program_id, expected_nonce)
    }

    /// 5 — owner closes the policy account and reclaims rent. The recipient
    /// is bound into the challenge so a stolen signature cannot redirect the
    /// rent to a different wallet.
    /// Audit C2 (Opção 4) + H6 + C1.
    #[instruction(discriminator = 5)]
    pub fn close_session(
        ctx: Ctx<CloseSession>,
        _init_authority_hash: Address,
        _session_index: u32,
        expected_nonce: u64,
    ) -> Result<(), ProgramError> {
        let current_ts: i64 = ctx.accounts.clock.unix_timestamp.into();
        let policy_addr = *ctx.accounts.session.address();
        ctx.accounts.close(expected_nonce)?;
        ctx.accounts.program.emit_event(
            &PolicyPaused {
                policy: policy_addr,
                ts: current_ts,
            },
            &ctx.accounts.event_authority,
            EventAuthority::BUMP,
        )?;
        Ok(())
    }

    /// 6 — permissionless cleanup. Anyone can close an expired session and
    /// route the rent to themselves.
    /// Audit C2 (Opção 4) + H6 + C1: `current_slot` from Clock.
    #[instruction(discriminator = 6)]
    pub fn close_expired_session(
        ctx: Ctx<CloseExpiredSession>,
        _init_authority_hash: Address,
        _session_index: u32,
    ) -> Result<(), ProgramError> {
        let current_slot: u64 = ctx.accounts.clock.slot.into();
        let current_ts: i64 = ctx.accounts.clock.unix_timestamp.into();
        let expires: u64 = ctx.accounts.session.expires_at_slot.into();
        require!(current_slot >= expires, SessionError::SessionStillActive);
        let policy_addr = *ctx.accounts.session.address();
        let recipient_view = ctx.accounts.recipient.to_account_view();
        ctx.accounts.session.close(recipient_view)?;
        ctx.accounts.program.emit_event(
            &PolicyPaused {
                policy: policy_addr,
                ts: current_ts,
            },
            &ctx.accounts.event_authority,
            EventAuthority::BUMP,
        )?;
        Ok(())
    }
}

#[error_code]
pub enum SessionError {
    SessionExpired = 6000,
    SessionMaxUsesReached,
    SessionDestinationNotAllowed,
    SessionAmountTooHigh,
    SessionStillActive,
    SessionWrongSigner,
    TooManyPrograms,
    InvalidNonce,
    AuthFailed,
    InvalidOwnerSlot,
    UnsupportedScheme,
    InvalidSignatureNonce, // Audit H3: replay protection per request
    ClearSigningRenderFailed,
}

impl From<AuthError> for SessionError {
    fn from(_e: AuthError) -> Self {
        SessionError::AuthFailed
    }
}

impl From<HumanMessageError> for SessionError {
    fn from(_e: HumanMessageError) -> Self {
        SessionError::ClearSigningRenderFailed
    }
}

// ── State ──
//
// Audit C2 (Opção 4) + H6: PDA seed includes init_authority_hash AND
// session_index → multiple sessions per (dwallet, init_authority) supported.
// Audit H3: `next_signature_nonce` makes each session signature single-use.

#[account(discriminator = 1, set_inner)]
#[seeds(b"session_key", dwallet: Address, init_authority_hash: Address, session_index: u32)]
pub struct SessionKeyPolicy {
    pub dwallet: Address,
    pub owner_slot: [u8; MEMBER_SLOT_LEN],
    pub init_authority_slot: [u8; MEMBER_SLOT_LEN],
    pub session_key: Address,
    pub session_index: u32,
    pub next_admin_nonce: u64,
    pub next_signature_nonce: u64,
    pub expires_at_slot: u64,
    pub max_amount_per_tx: u64,
    pub used_count: u32,
    pub max_uses: u32,
    pub allowed_program_count: u8,
    pub _pad: [u8; 1],
    pub allowed_programs_flat: [u8; 256], // 8 × 32 bytes
}

/// Audit C2 (Opção 4) helper.
#[inline]
fn init_authority_hash_from_slot(slot: &[u8; MEMBER_SLOT_LEN]) -> Address {
    Address::from(hashv(&[slot]))
}

// ── CreateSession ──────────────────────────────────────────────

#[derive(Accounts)]
#[instruction(init_authority_slot: [u8; 34], init_authority_hash: Address, session_index: u32)]
pub struct CreateSession {
    pub dwallet_account: UncheckedAccount,

    #[account(init, payer = payer, address = SessionKeyPolicy::seeds(
        dwallet_account.address(),
        &init_authority_hash,
        session_index
    ))]
    pub session: Account<SessionKeyPolicy>,

    pub instructions_sysvar: UncheckedAccount,
    pub clock: Sysvar<Clock>,

    #[account(mut)]
    pub payer: Signer,

    pub rent: Sysvar<Rent>,
    pub system_program: Program<SystemProgram>,
    pub event_authority: EventAuthority,
    pub program: Program<SessionKeys>,
}

impl CreateSession {
    #[inline(always)]
    #[allow(clippy::too_many_arguments)]
    pub fn create(
        &mut self,
        init_authority_slot: [u8; MEMBER_SLOT_LEN],
        init_authority_hash: Address,
        session_index: u32,
        owner_slot: [u8; MEMBER_SLOT_LEN],
        session_key: Address,
        expires_at_slot: u64,
        max_amount_per_tx: u64,
        max_uses: u32,
    ) -> Result<(), ProgramError> {
        // Audit C2 (Opção 4): hash<->slot consistency.
        let computed = init_authority_hash_from_slot(&init_authority_slot);
        require!(
            computed == init_authority_hash,
            SessionError::InvalidOwnerSlot
        );
        validate_slot(&init_authority_slot).map_err(|_| SessionError::InvalidOwnerSlot)?;
        require!(
            init_authority_slot[0] != SCHEME_WEBAUTHN,
            SessionError::UnsupportedScheme
        );

        validate_slot(&owner_slot).map_err(|_| SessionError::InvalidOwnerSlot)?;
        require!(
            owner_slot[0] != SCHEME_WEBAUTHN,
            SessionError::UnsupportedScheme
        );

        // Audit C2 (Opção 4): verify init precompile signature. The challenge
        // binds session_index too so the user explicitly authorizes which
        // session slot to occupy.
        let dwallet_addr = *self.dwallet_account.address();
        let challenge = challenges::init_policy_challenge(
            &dwallet_addr,
            &init_authority_slot,
            session_index,
            &owner_slot,
            &session_key,
            expires_at_slot,
            max_amount_per_tx,
            max_uses,
        );
        check_sysvar_addr(self.instructions_sysvar.address())?;
        let sysvar_view = self.instructions_sysvar.to_account_view();
        let sysvar_data_ref = sysvar_view
            .try_borrow()
            .map_err(|_| SessionError::AuthFailed)?;
        verify_signature(VerifyInput {
            member_slot: &init_authority_slot,
            challenge: &challenge,
            instructions_sysvar_data: &sysvar_data_ref,
            webauthn_auth_data: &[],
            webauthn_client_data_json: &[],
        })
        .map_err(|_| SessionError::AuthFailed)?;
        drop(sysvar_data_ref);

        self.session.set_inner(SessionKeyPolicyInner {
            dwallet: dwallet_addr,
            owner_slot,
            init_authority_slot,
            session_key,
            session_index,
            next_admin_nonce: 0,
            next_signature_nonce: 0,
            expires_at_slot,
            max_amount_per_tx,
            used_count: 0,
            max_uses,
            allowed_program_count: 0,
            _pad: [0u8; 1],
            allowed_programs_flat: [0u8; 256],
        });
        Ok(())
    }
}

// ── RequestSignatureViaSession (session keypair signs, not owner) ──

#[derive(Accounts)]
#[instruction(init_authority_hash: Address, session_index: u32)]
pub struct RequestSignatureViaSession {
    pub dwallet_account: UncheckedAccount,

    #[account(mut, address = SessionKeyPolicy::seeds(
        dwallet_account.address(),
        &init_authority_hash,
        session_index
    ))]
    pub session: Account<SessionKeyPolicy>,

    /// Session's keypair — must sign every approve_message. Generated by the
    /// dev's app, never the user's main wallet.
    pub session_signer: Signer,

    pub coordinator: UncheckedAccount,

    #[account(mut)]
    pub message_approval: UncheckedAccount,

    #[account(mut)]
    pub payer: Signer,

    pub cpi_authority: UncheckedAccount,
    pub caller_program: UncheckedAccount,
    pub dwallet_program: UncheckedAccount,
    pub clock: Sysvar<Clock>,
    pub system_program: Program<SystemProgram>,
    pub event_authority: EventAuthority,
    pub program: Program<SessionKeys>,
}

impl RequestSignatureViaSession {
    #[inline(always)]
    #[allow(clippy::too_many_arguments)]
    pub fn request(
        &mut self,
        message_digest: [u8; 32],
        metadata_digest: [u8; 32],
        user_pubkey: [u8; 32],
        signature_scheme: u16,
        message_approval_bump: u8,
        cpi_authority_bump: u8,
        amount: u64,
        destination_program: Address,
        current_slot: u64,
        expected_signature_nonce: u64,
    ) -> Result<(), ProgramError> {
        let signer_matches = self.session_signer.address() == &self.session.session_key;
        require!(signer_matches, SessionError::SessionWrongSigner);

        // Audit H3: monotonic per-request nonce. Each session signature is
        // single-use — even if the session_key leaks, attacker can submit
        // each captured tx at most once.
        let on_chain_nonce: u64 = self.session.next_signature_nonce.into();
        require!(
            expected_signature_nonce == on_chain_nonce,
            SessionError::InvalidSignatureNonce
        );

        let expires: u64 = self.session.expires_at_slot.into();
        require!(current_slot < expires, SessionError::SessionExpired);

        let used: u32 = self.session.used_count.into();
        let cap: u32 = self.session.max_uses.into();
        require!(used < cap, SessionError::SessionMaxUsesReached);

        let max_amount: u64 = self.session.max_amount_per_tx.into();
        require!(amount <= max_amount, SessionError::SessionAmountTooHigh);

        let count = self.session.allowed_program_count as usize;
        let dest_bytes = destination_program.as_array();
        let mut allowed = false;
        for i in 0..count {
            let off = i * 32;
            if &self.session.allowed_programs_flat[off..off + 32] == dest_bytes.as_slice() {
                allowed = true;
                break;
            }
        }
        require!(allowed, SessionError::SessionDestinationNotAllowed);

        let policy_addr = *self.session.address();
        let dwallet_addr = *self.dwallet_account.address();
        let expected_metadata_digest = challenges::request_metadata_digest(
            &policy_addr,
            &dwallet_addr,
            &self.session.session_key,
            &message_digest,
            amount,
            &destination_program,
            &user_pubkey,
            signature_scheme,
            on_chain_nonce,
        );
        require!(
            metadata_digest == expected_metadata_digest,
            SessionError::AuthFailed
        );

        // Audit H3: increment signature nonce atomically before CPI.
        self.session.next_signature_nonce = (on_chain_nonce + 1).into();
        self.session.used_count = (used + 1).into();
        require!(
            validate_ika_cpi_accounts(
                &self.dwallet_program.to_account_view(),
                &self.dwallet_account.to_account_view(),
            ),
            SessionError::AuthFailed
        );

        let dwallet_ctx = DWalletContext {
            dwallet_program: self.dwallet_program.to_account_view(),
            cpi_authority: self.cpi_authority.to_account_view(),
            caller_program: self.caller_program.to_account_view(),
            cpi_authority_bump,
        };
        dwallet_ctx.approve_message(
            self.coordinator.to_account_view(),
            self.message_approval.to_account_view(),
            self.dwallet_account.to_account_view(),
            self.payer.to_account_view(),
            self.system_program.to_account_view(),
            message_digest,
            metadata_digest,
            user_pubkey,
            signature_scheme,
            message_approval_bump,
        )
    }
}

// ── AdminAction (challenge-based) ──────────────────────────────

#[derive(Accounts)]
#[instruction(init_authority_hash: Address, session_index: u32)]
pub struct AdminAction {
    pub dwallet_account: UncheckedAccount,

    #[account(mut, address = SessionKeyPolicy::seeds(
        dwallet_account.address(),
        &init_authority_hash,
        session_index
    ))]
    pub session: Account<SessionKeyPolicy>,

    pub instructions_sysvar: UncheckedAccount,
    pub clock: Sysvar<Clock>,

    #[account(mut)]
    pub payer: Signer,
    pub event_authority: EventAuthority,
    pub program: Program<SessionKeys>,
}

impl AdminAction {
    fn run<F>(&mut self, expected_nonce: u64, build_challenge: F) -> Result<(), ProgramError>
    where
        F: FnOnce(
            &Address,
            &Address,
            &[u8; MEMBER_SLOT_LEN],
            u64,
        ) -> Result<[u8; 32], HumanMessageError>,
    {
        let dwallet_addr = *self.dwallet_account.address();
        let policy_addr = *self.session.address();
        let owner_slot = self.session.owner_slot;
        let on_chain_nonce: u64 = self.session.next_admin_nonce.into();
        let challenge = build_challenge(&dwallet_addr, &policy_addr, &owner_slot, on_chain_nonce)
            .map_err(SessionError::from)?;

        check_sysvar_addr(self.instructions_sysvar.address())?;
        let sysvar_view = self.instructions_sysvar.to_account_view();
        let sysvar_data_ref = sysvar_view
            .try_borrow()
            .map_err(|_| SessionError::AuthFailed)?;

        let new_nonce = verify_owner_admin(
            expected_nonce,
            on_chain_nonce,
            &owner_slot,
            &challenge,
            &sysvar_data_ref,
        )
        .map_err(map_auth_err)?;
        drop(sysvar_data_ref);

        self.session.next_admin_nonce = new_nonce.into();
        Ok(())
    }

    #[inline(always)]
    pub fn revoke(&mut self, expected_nonce: u64) -> Result<(), ProgramError> {
        self.run(expected_nonce, |dw, policy, owner, n| {
            challenges::revoke_session_challenge(dw, policy, n, owner)
        })?;
        self.session.expires_at_slot = 0u64.into();
        Ok(())
    }

    #[inline(always)]
    pub fn add_program(
        &mut self,
        program_id: Address,
        expected_nonce: u64,
    ) -> Result<(), ProgramError> {
        self.run(expected_nonce, |dw, policy, owner, n| {
            challenges::add_allowed_program_challenge(dw, policy, &program_id, n, owner)
        })?;
        let count = self.session.allowed_program_count as usize;
        let bytes = program_id.as_array();
        for i in 0..count {
            let off = i * 32;
            if &self.session.allowed_programs_flat[off..off + 32] == bytes.as_slice() {
                return Ok(());
            }
        }
        require!(count < MAX_ALLOWED_PROGRAMS, SessionError::TooManyPrograms);
        let off = count * 32;
        self.session.allowed_programs_flat[off..off + 32].copy_from_slice(bytes.as_slice());
        self.session.allowed_program_count = (count as u8) + 1;
        Ok(())
    }

    #[inline(always)]
    pub fn remove_program(
        &mut self,
        program_id: Address,
        expected_nonce: u64,
    ) -> Result<(), ProgramError> {
        self.run(expected_nonce, |dw, policy, owner, n| {
            challenges::remove_allowed_program_challenge(dw, policy, &program_id, n, owner)
        })?;
        let count = self.session.allowed_program_count as usize;
        let bytes = program_id.as_array();
        for i in 0..count {
            let off = i * 32;
            if &self.session.allowed_programs_flat[off..off + 32] == bytes.as_slice() {
                let last = (count - 1) * 32;
                if i != count - 1 {
                    let mut tail = [0u8; 32];
                    tail.copy_from_slice(&self.session.allowed_programs_flat[last..last + 32]);
                    self.session.allowed_programs_flat[off..off + 32].copy_from_slice(&tail);
                }
                self.session.allowed_programs_flat[last..last + 32].copy_from_slice(&[0u8; 32]);
                self.session.allowed_program_count = (count - 1) as u8;
                return Ok(());
            }
        }
        Ok(())
    }
}

// ── CloseSession (owner challenge — recipient bound into challenge) ──

#[derive(Accounts)]
#[instruction(init_authority_hash: Address, session_index: u32)]
pub struct CloseSession {
    pub dwallet_account: UncheckedAccount,

    #[account(mut, address = SessionKeyPolicy::seeds(
        dwallet_account.address(),
        &init_authority_hash,
        session_index
    ))]
    pub session: Account<SessionKeyPolicy>,

    pub instructions_sysvar: UncheckedAccount,
    pub clock: Sysvar<Clock>,

    #[account(mut)]
    pub payer: Signer,

    /// Where the reclaimed rent lamports go. Bound into the close_session_challenge
    /// so a stolen signature can't redirect rent.
    #[account(mut)]
    pub recipient: UncheckedAccount,
    pub event_authority: EventAuthority,
    pub program: Program<SessionKeys>,
}

impl CloseSession {
    #[inline(always)]
    pub fn close(&mut self, expected_nonce: u64) -> Result<(), ProgramError> {
        let dwallet_addr = *self.dwallet_account.address();
        let policy_addr = *self.session.address();
        let owner_slot = self.session.owner_slot;
        let on_chain_nonce: u64 = self.session.next_admin_nonce.into();
        let recipient_addr = *self.recipient.address();
        let challenge = challenges::close_session_challenge(
            &dwallet_addr,
            &policy_addr,
            &recipient_addr,
            on_chain_nonce,
            &owner_slot,
        )
        .map_err(SessionError::from)?;

        check_sysvar_addr(self.instructions_sysvar.address())?;
        let sysvar_view = self.instructions_sysvar.to_account_view();
        let sysvar_data_ref = sysvar_view
            .try_borrow()
            .map_err(|_| SessionError::AuthFailed)?;
        let _new_nonce = verify_owner_admin(
            expected_nonce,
            on_chain_nonce,
            &owner_slot,
            &challenge,
            &sysvar_data_ref,
        )
        .map_err(map_auth_err)?;
        drop(sysvar_data_ref);

        // Account is being closed, so we don't write new_nonce back. Close
        // transfers the lamports to recipient and zeros the data so the
        // runtime garbage-collects it after this tx.
        let recipient_view = self.recipient.to_account_view();
        self.session.close(recipient_view)?;
        Ok(())
    }
}

// ── CloseExpiredSession (permissionless) ──────────────────────

#[derive(Accounts)]
#[instruction(init_authority_hash: Address, session_index: u32)]
pub struct CloseExpiredSession {
    pub dwallet_account: UncheckedAccount,

    #[account(mut, address = SessionKeyPolicy::seeds(
        dwallet_account.address(),
        &init_authority_hash,
        session_index
    ))]
    pub session: Account<SessionKeyPolicy>,

    /// Where the reclaimed rent lamports go. Caller picks this; usually the
    /// gas sponsor that submits this cleanup tx.
    #[account(mut)]
    pub recipient: UncheckedAccount,

    pub clock: Sysvar<Clock>,

    #[account(mut)]
    pub payer: Signer,
    pub event_authority: EventAuthority,
    pub program: Program<SessionKeys>,
}

#[inline]
fn check_sysvar_addr(addr: &Address) -> Result<(), ProgramError> {
    check_sysvar_address(addr).map_err(|_| SessionError::AuthFailed.into())
}

fn map_auth_err(e: AuthError) -> SessionError {
    match e {
        AuthError::InvalidNonce => SessionError::InvalidNonce,
        AuthError::UnsupportedScheme => SessionError::UnsupportedScheme,
        _ => SessionError::AuthFailed,
    }
}

// ── Events ─────────────────────────────────────────────────────

#[event(discriminator = 0)]
pub struct PolicyDeployed {
    pub policy: Address,
    pub dwallet: Address,
    pub ts: i64,
}

#[event(discriminator = 1)]
pub struct SignatureRequested {
    pub policy: Address,
    pub request_hash: Address,
    pub ts: i64,
}

#[event(discriminator = 2)]
pub struct SignatureApproved {
    pub policy: Address,
    pub request_hash: Address,
    pub ts: i64,
}

#[event(discriminator = 4)]
pub struct PolicyPaused {
    pub policy: Address,
    pub ts: i64,
}

#[event(discriminator = 5)]
pub struct PolicyResumed {
    pub policy: Address,
    pub ts: i64,
}
