//! Clear-signing renderers — turn the typed parameters of a governance
//! challenge into a deterministic ASCII message that the approver reads
//! before signing, and that the on-chain handler recomputes from the
//! same typed parameters.
//!
//! Design constraints:
//!  * `#![no_std]`-compatible: no `String`, no `format!`, no heap, no `std`.
//!  * Bounded output: every rendered message fits in
//!    [`MAX_HUMAN_MESSAGE_BYTES`] = 512.
//!  * ASCII-only: every byte produced is `0x20..=0x7E`. The output is also
//!    valid UTF-8.
//!  * Deterministic byte-by-byte across Rust, TypeScript and Go mirrors.
//!
//! The TypeScript mirror is `ika-backend/src/recovery/clear_signing.ts`
//! and the Go mirror is `gateway/internal/auth/clear_signing.go`. Golden
//! vectors are generated by Rust (`contracts/auth/examples/gen_challenge_vectors.rs`)
//! and consumed in CI by all three languages — any wire-format change
//! must regenerate the vectors in the same commit.

use crate::{id_len_for_scheme, MEMBER_SLOT_LEN};
use solana_address::Address;

/// Maximum byte length of a rendered clear-signing message.
///
/// Originally frozen at 512 in the v2 spec; raised to 768 on 2026-05-14
/// because `quorum-contribute` carries the full session snapshot
/// (session, member_slot, dwallet, three digests, user_pubkey, amount,
/// destination, expires_at) plus the member-slot text (e.g. `scheme:0;id:`
/// followed by 64 hex chars for Ed25519), which exceeds 512 in worst case.
/// 768 keeps the `u16 LE` length-prefix valid (max 65535) and still bounds
/// SBF stack usage. Reduce only after CU profiling shows headroom.
pub const MAX_HUMAN_MESSAGE_BYTES: usize = 768;

/// Bitcoin / Solana base58 alphabet (no `0`, `O`, `I`, `l`).
const B58_ALPHABET: &[u8; 58] = b"123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HumanMessageError {
    /// Writing the next chunk would exceed [`MAX_HUMAN_MESSAGE_BYTES`].
    BufferTooSmall,
    /// Caller passed a string with non-ASCII bytes (the on-chain renderer
    /// only emits ASCII, so this should never happen with well-formed
    /// template literals).
    NonAscii,
    /// Slot layout failed validation (unknown scheme, etc.).
    InvalidSlot,
}

/// ASCII writer that appends into a fixed 512-byte buffer.
///
/// All helpers (`write_str`, `write_uXX_dec`, `write_hex_lower`,
/// `write_base58_32`, `write_member_slot`, `write_option_u64`) keep an
/// internal cursor and fail with [`HumanMessageError::BufferTooSmall`]
/// the moment the next chunk would overflow.
pub struct MsgWriter<'a> {
    buf: &'a mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    len: usize,
}

impl<'a> MsgWriter<'a> {
    #[inline]
    pub fn new(buf: &'a mut [u8; MAX_HUMAN_MESSAGE_BYTES]) -> Self {
        Self { buf, len: 0 }
    }

    #[inline]
    pub fn len(&self) -> usize {
        self.len
    }

    #[inline]
    pub fn is_empty(&self) -> bool {
        self.len == 0
    }

    #[inline]
    pub fn as_bytes(&self) -> &[u8] {
        &self.buf[..self.len]
    }

    #[inline]
    fn push_byte(&mut self, b: u8) -> Result<(), HumanMessageError> {
        if self.len >= MAX_HUMAN_MESSAGE_BYTES {
            return Err(HumanMessageError::BufferTooSmall);
        }
        self.buf[self.len] = b;
        self.len += 1;
        Ok(())
    }

    #[inline]
    fn push_bytes(&mut self, bytes: &[u8]) -> Result<(), HumanMessageError> {
        if self.len.saturating_add(bytes.len()) > MAX_HUMAN_MESSAGE_BYTES {
            return Err(HumanMessageError::BufferTooSmall);
        }
        self.buf[self.len..self.len + bytes.len()].copy_from_slice(bytes);
        self.len += bytes.len();
        Ok(())
    }

    /// Append an ASCII literal. Non-ASCII bytes are rejected — every
    /// template literal in this module is hand-checked.
    #[inline]
    pub fn write_str(&mut self, s: &str) -> Result<(), HumanMessageError> {
        for &b in s.as_bytes() {
            if !(0x20..=0x7E).contains(&b) {
                return Err(HumanMessageError::NonAscii);
            }
        }
        self.push_bytes(s.as_bytes())
    }

    pub fn write_u8_dec(&mut self, v: u8) -> Result<(), HumanMessageError> {
        self.write_u64_dec(v as u64)
    }

    pub fn write_u16_dec(&mut self, v: u16) -> Result<(), HumanMessageError> {
        self.write_u64_dec(v as u64)
    }

    pub fn write_u32_dec(&mut self, v: u32) -> Result<(), HumanMessageError> {
        self.write_u64_dec(v as u64)
    }

    pub fn write_u64_dec(&mut self, v: u64) -> Result<(), HumanMessageError> {
        // Max u64 = 20 digits.
        let mut digits = [0u8; 20];
        let mut i = digits.len();
        let mut n = v;
        if n == 0 {
            return self.push_byte(b'0');
        }
        while n > 0 {
            i -= 1;
            digits[i] = b'0' + ((n % 10) as u8);
            n /= 10;
        }
        self.push_bytes(&digits[i..])
    }

    pub fn write_i64_dec(&mut self, v: i64) -> Result<(), HumanMessageError> {
        if v < 0 {
            self.push_byte(b'-')?;
            // Use wrapping_neg + cast to u64 to handle i64::MIN cleanly.
            let abs = (v as i128).unsigned_abs() as u64;
            self.write_u64_dec(abs)
        } else {
            self.write_u64_dec(v as u64)
        }
    }

    pub fn write_hex_lower(&mut self, bytes: &[u8]) -> Result<(), HumanMessageError> {
        const HEX: &[u8; 16] = b"0123456789abcdef";
        if self.len.saturating_add(bytes.len() * 2) > MAX_HUMAN_MESSAGE_BYTES {
            return Err(HumanMessageError::BufferTooSmall);
        }
        for &b in bytes {
            self.buf[self.len] = HEX[(b >> 4) as usize];
            self.buf[self.len + 1] = HEX[(b & 0x0F) as usize];
            self.len += 2;
        }
        Ok(())
    }

    /// base58 encoding of exactly 32 bytes (Solana address layout). Output
    /// is between 32 and 44 ASCII chars; we reserve up to 44.
    pub fn write_base58_32(&mut self, addr: &[u8; 32]) -> Result<(), HumanMessageError> {
        let mut out = [0u8; 44];
        let len = encode_base58_32(addr, &mut out);
        self.push_bytes(&out[..len])
    }

    /// Renders a 34-byte member slot as `scheme:{n};id:{hex2*L}` where `L`
    /// depends on the scheme tag (32 / 20 / 33 / 33 / 32 for schemes 0..=4).
    pub fn write_member_slot(
        &mut self,
        slot: &[u8; MEMBER_SLOT_LEN],
    ) -> Result<(), HumanMessageError> {
        let scheme = slot[0];
        let id_len = match id_len_for_scheme(scheme) {
            Ok(l) => l,
            Err(_) => return Err(HumanMessageError::InvalidSlot),
        };
        self.write_str("scheme:")?;
        self.write_u8_dec(scheme)?;
        self.write_str(";id:")?;
        self.write_hex_lower(&slot[1..1 + id_len])
    }

    /// `none` when `some == 0`, decimal of `v` otherwise.
    pub fn write_option_u64(&mut self, some: u8, v: u64) -> Result<(), HumanMessageError> {
        if some == 0 {
            self.write_str("none")
        } else {
            self.write_u64_dec(v)
        }
    }
}

/// Encodes 32 bytes into a base58 ASCII string. Returns the number of
/// bytes written (32..=44). Output buffer must be at least 44 bytes.
fn encode_base58_32(input: &[u8; 32], out: &mut [u8; 44]) -> usize {
    // Count leading zeros — each one becomes a '1' in base58.
    let mut leading_zeros = 0usize;
    while leading_zeros < input.len() && input[leading_zeros] == 0 {
        leading_zeros += 1;
    }

    // Allocate a scratch buffer big enough for the worst-case base58 output.
    // 32 bytes * log_58(256) ≈ 43.8, so 44 is the worst case.
    let mut digits = [0u8; 44];
    let mut digits_len = 0usize;

    for &byte in &input[leading_zeros..] {
        let mut carry = byte as u32;
        for d in digits[..digits_len].iter_mut() {
            carry += (*d as u32) << 8;
            *d = (carry % 58) as u8;
            carry /= 58;
        }
        while carry > 0 {
            if digits_len >= digits.len() {
                // Should be unreachable for 32-byte inputs.
                break;
            }
            digits[digits_len] = (carry % 58) as u8;
            digits_len += 1;
            carry /= 58;
        }
    }

    // Write leading '1's for each leading zero byte, then reverse-emit digits.
    let total_len = leading_zeros + digits_len;
    if total_len > out.len() {
        // Truncate — should never happen for 32-byte inputs given the worst-case 44.
        return out.len();
    }

    for slot in out.iter_mut().take(leading_zeros) {
        *slot = B58_ALPHABET[0]; // '1'
    }
    for (i, slot) in out
        .iter_mut()
        .skip(leading_zeros)
        .take(digits_len)
        .enumerate()
    {
        *slot = B58_ALPHABET[digits[digits_len - 1 - i] as usize];
    }

    total_len
}

#[cfg(any(test, feature = "host-test"))]
mod tests {
    use super::*;

    #[test]
    fn write_u64_dec_zero() {
        let mut buf = [0u8; MAX_HUMAN_MESSAGE_BYTES];
        let mut w = MsgWriter::new(&mut buf);
        w.write_u64_dec(0).unwrap();
        assert_eq!(w.as_bytes(), b"0");
    }

    #[test]
    fn write_u64_dec_max() {
        let mut buf = [0u8; MAX_HUMAN_MESSAGE_BYTES];
        let mut w = MsgWriter::new(&mut buf);
        w.write_u64_dec(u64::MAX).unwrap();
        assert_eq!(w.as_bytes(), b"18446744073709551615");
    }

    #[test]
    fn write_i64_dec_negative() {
        let mut buf = [0u8; MAX_HUMAN_MESSAGE_BYTES];
        let mut w = MsgWriter::new(&mut buf);
        w.write_i64_dec(-42).unwrap();
        assert_eq!(w.as_bytes(), b"-42");
    }

    #[test]
    fn write_i64_dec_min() {
        let mut buf = [0u8; MAX_HUMAN_MESSAGE_BYTES];
        let mut w = MsgWriter::new(&mut buf);
        w.write_i64_dec(i64::MIN).unwrap();
        assert_eq!(w.as_bytes(), b"-9223372036854775808");
    }

    #[test]
    fn write_hex_lower_basic() {
        let mut buf = [0u8; MAX_HUMAN_MESSAGE_BYTES];
        let mut w = MsgWriter::new(&mut buf);
        w.write_hex_lower(&[0xde, 0xad, 0xbe, 0xef]).unwrap();
        assert_eq!(w.as_bytes(), b"deadbeef");
    }

    #[test]
    fn write_member_slot_ed25519() {
        let mut slot = [0u8; MEMBER_SLOT_LEN];
        slot[0] = 0;
        for i in 0..32 {
            slot[1 + i] = i as u8;
        }
        let mut buf = [0u8; MAX_HUMAN_MESSAGE_BYTES];
        let mut w = MsgWriter::new(&mut buf);
        w.write_member_slot(&slot).unwrap();
        assert_eq!(
            w.as_bytes(),
            b"scheme:0;id:000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
        );
    }

    #[test]
    fn write_member_slot_secp256k1() {
        let mut slot = [0u8; MEMBER_SLOT_LEN];
        slot[0] = 1;
        for i in 0..20 {
            slot[1 + i] = 0x42;
        }
        let mut buf = [0u8; MAX_HUMAN_MESSAGE_BYTES];
        let mut w = MsgWriter::new(&mut buf);
        w.write_member_slot(&slot).unwrap();
        assert_eq!(
            w.as_bytes(),
            b"scheme:1;id:4242424242424242424242424242424242424242"
        );
    }

    #[test]
    fn write_option_u64_none() {
        let mut buf = [0u8; MAX_HUMAN_MESSAGE_BYTES];
        let mut w = MsgWriter::new(&mut buf);
        w.write_option_u64(0, 999).unwrap();
        assert_eq!(w.as_bytes(), b"none");
    }

    #[test]
    fn write_option_u64_some() {
        let mut buf = [0u8; MAX_HUMAN_MESSAGE_BYTES];
        let mut w = MsgWriter::new(&mut buf);
        w.write_option_u64(1, 42).unwrap();
        assert_eq!(w.as_bytes(), b"42");
    }

    #[test]
    fn write_base58_all_zeros() {
        let mut buf = [0u8; MAX_HUMAN_MESSAGE_BYTES];
        let mut w = MsgWriter::new(&mut buf);
        w.write_base58_32(&[0u8; 32]).unwrap();
        // 32 zero bytes → 32 leading '1's in base58.
        assert_eq!(w.as_bytes(), &b"11111111111111111111111111111111"[..]);
    }

    #[test]
    fn write_base58_system_program() {
        // Solana System Program address bytes (all zeros) base58 is "11111111111111111111111111111111".
        let mut buf = [0u8; MAX_HUMAN_MESSAGE_BYTES];
        let mut w = MsgWriter::new(&mut buf);
        w.write_base58_32(&[0u8; 32]).unwrap();
        assert_eq!(w.as_bytes(), b"11111111111111111111111111111111");
    }

    #[test]
    fn buffer_overflow() {
        let mut buf = [0u8; MAX_HUMAN_MESSAGE_BYTES];
        let mut w = MsgWriter::new(&mut buf);
        // Write MAX-1 'a's, then try to write more than 1 byte.
        for _ in 0..(MAX_HUMAN_MESSAGE_BYTES - 1) {
            w.write_str("a").unwrap();
        }
        // Writing a 2-byte literal must fail.
        assert!(matches!(
            w.write_str("ab"),
            Err(HumanMessageError::BufferTooSmall)
        ));
        // But a single byte still fits.
        w.write_str("b").unwrap();
        // Now the buffer is full.
        assert!(matches!(
            w.write_str("c"),
            Err(HumanMessageError::BufferTooSmall)
        ));
    }
}

// ============================================================================
// Rendered templates — one function per (operation) in the spec.
// ============================================================================
//
// Every renderer takes:
//   * a pre-allocated 512-byte buffer (no heap),
//   * the typed parameters of the operation,
// and returns the byte length of the rendered ASCII message.
//
// The output is plain ASCII (`0x20..=0x7E`), valid UTF-8, and matches the
// spec in `docs/SPEC_CLEAR_SIGNING_FROZEN.md` byte-for-byte. Any edit here
// must also update the TS/Go mirrors and regenerate the golden vectors.
//
// Naming: each function mirrors the corresponding `*_challenge` in
// `challenge.rs` (or in `contracts/*/src/challenges.rs` for Phase 2).

// ── Phase 1: rules-policy recovery (3) ───────────────────────────

pub fn primary_recover_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    dwallet: &Address,
    message_digest: &[u8; 32],
    metadata_digest: &[u8; 32],
    user_pubkey: &[u8; 32],
    signature_scheme: u16,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Recover dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    w.write_str(" for message ")?;
    w.write_hex_lower(message_digest)?;
    w.write_str(" metadata ")?;
    w.write_hex_lower(metadata_digest)?;
    w.write_str(" scheme ")?;
    w.write_u16_dec(signature_scheme)?;
    w.write_str(" user ")?;
    w.write_hex_lower(user_pubkey)?;
    Ok(w.len())
}

#[allow(clippy::too_many_arguments)]
pub fn quorum_session_open_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    dwallet: &Address,
    amount: u64,
    destination: &[u8; 32],
    message_digest: &[u8; 32],
    metadata_digest: &[u8; 32],
    signature_scheme: u16,
    expires_at_unix: i64,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Open quorum session for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    w.write_str(" amount ")?;
    w.write_u64_dec(amount)?;
    w.write_str(" destination ")?;
    w.write_hex_lower(destination)?;
    w.write_str(" message ")?;
    w.write_hex_lower(message_digest)?;
    w.write_str(" metadata ")?;
    w.write_hex_lower(metadata_digest)?;
    w.write_str(" scheme ")?;
    w.write_u16_dec(signature_scheme)?;
    w.write_str(" expires ")?;
    w.write_i64_dec(expires_at_unix)?;
    Ok(w.len())
}

#[allow(clippy::too_many_arguments)]
pub fn quorum_contribute_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    session: &Address,
    member_slot: &[u8; MEMBER_SLOT_LEN],
    dwallet: &Address,
    amount: u64,
    destination: &[u8; 32],
    message_digest: &[u8; 32],
    metadata_digest: &[u8; 32],
    user_pubkey: &[u8; 32],
    signature_scheme: u16,
    expires_at_unix: i64,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Contribute to quorum session ")?;
    w.write_base58_32(session.as_array())?;
    w.write_str(" as member ")?;
    w.write_member_slot(member_slot)?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    w.write_str(" amount ")?;
    w.write_u64_dec(amount)?;
    w.write_str(" destination ")?;
    w.write_hex_lower(destination)?;
    w.write_str(" message ")?;
    w.write_hex_lower(message_digest)?;
    w.write_str(" metadata ")?;
    w.write_hex_lower(metadata_digest)?;
    w.write_str(" scheme ")?;
    w.write_u16_dec(signature_scheme)?;
    w.write_str(" user ")?;
    w.write_hex_lower(user_pubkey)?;
    w.write_str(" expires ")?;
    w.write_i64_dec(expires_at_unix)?;
    Ok(w.len())
}

// ── Phase 1: rules-policy admin (12) ─────────────────────────────

pub fn admin_add_member_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    new_member_slot: &[u8; MEMBER_SLOT_LEN],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Add member ")?;
    w.write_member_slot(new_member_slot)?;
    w.write_str(" to policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn admin_remove_member_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    member_slot: &[u8; MEMBER_SLOT_LEN],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Remove member ")?;
    w.write_member_slot(member_slot)?;
    w.write_str(" from policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn admin_add_destination_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    destination: &[u8; 32],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Allow destination ")?;
    w.write_hex_lower(destination)?;
    w.write_str(" on policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn admin_remove_destination_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    destination: &[u8; 32],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Block destination ")?;
    w.write_hex_lower(destination)?;
    w.write_str(" on policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn admin_revoke_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Revoke policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn admin_set_primary_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    new_primary_slot: &[u8; MEMBER_SLOT_LEN],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Set primary to ")?;
    w.write_member_slot(new_primary_slot)?;
    w.write_str(" on policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn admin_set_quorum_threshold_immediate_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    new_threshold: u8,
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Set quorum threshold to ")?;
    w.write_u8_dec(new_threshold)?;
    w.write_str(" immediately on policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn admin_set_daily_limit_immediate_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    new_some: u8,
    new_limit: u64,
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Set daily limit to ")?;
    w.write_option_u64(new_some, new_limit)?;
    w.write_str(" immediately on policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn admin_set_cooldown_immediate_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    new_cooldown_seconds: u64,
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Set cooldown to ")?;
    w.write_u64_dec(new_cooldown_seconds)?;
    w.write_str(" seconds immediately on policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn admin_propose_quorum_threshold_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    new_threshold: u8,
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Propose quorum threshold ")?;
    w.write_u8_dec(new_threshold)?;
    w.write_str(" on policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn admin_propose_daily_limit_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    new_some: u8,
    new_limit: u64,
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Propose daily limit ")?;
    w.write_option_u64(new_some, new_limit)?;
    w.write_str(" on policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn admin_propose_cooldown_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    new_cooldown_seconds: u64,
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Propose cooldown ")?;
    w.write_u64_dec(new_cooldown_seconds)?;
    w.write_str(" seconds on policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

// ── Phase 1: rules-policy OIDC (2) ───────────────────────────────

pub fn oidc_session_open_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    dwallet: &Address,
    not_after_unix_ts: u64,
    eph_pk: &[u8; 32],
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Open OIDC session for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    w.write_str(" until ")?;
    w.write_u64_dec(not_after_unix_ts)?;
    w.write_str(" using ephemeral key ")?;
    w.write_hex_lower(eph_pk)?;
    Ok(w.len())
}

pub fn oidc_primary_use_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    session: &Address,
    dwallet: &Address,
    message_digest: &[u8; 32],
    metadata_digest: &[u8; 32],
    user_pubkey: &[u8; 32],
    signature_scheme: u16,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Authorize OIDC session ")?;
    w.write_base58_32(session.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    w.write_str(" message ")?;
    w.write_hex_lower(message_digest)?;
    w.write_str(" metadata ")?;
    w.write_hex_lower(metadata_digest)?;
    w.write_str(" scheme ")?;
    w.write_u16_dec(signature_scheme)?;
    w.write_str(" user ")?;
    w.write_hex_lower(user_pubkey)?;
    Ok(w.len())
}

pub fn passkey_session_open_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    dwallet: &Address,
    not_after_unix_ts: u64,
    eph_pk: &[u8; 32],
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Open passkey session for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    w.write_str(" until ")?;
    w.write_u64_dec(not_after_unix_ts)?;
    w.write_str(" using ephemeral key ")?;
    w.write_hex_lower(eph_pk)?;
    Ok(w.len())
}

pub fn passkey_primary_use_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    session: &Address,
    dwallet: &Address,
    message_digest: &[u8; 32],
    metadata_digest: &[u8; 32],
    user_pubkey: &[u8; 32],
    signature_scheme: u16,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Authorize passkey session ")?;
    w.write_base58_32(session.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    w.write_str(" message ")?;
    w.write_hex_lower(message_digest)?;
    w.write_str(" metadata ")?;
    w.write_hex_lower(metadata_digest)?;
    w.write_str(" scheme ")?;
    w.write_u16_dec(signature_scheme)?;
    w.write_str(" user ")?;
    w.write_hex_lower(user_pubkey)?;
    Ok(w.len())
}

// ── Phase 2: allowlist-destinations admin (4) ────────────────────

pub fn allowlist_add_destination_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    destination: &[u8; 32],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Allow destination ")?;
    w.write_hex_lower(destination)?;
    w.write_str(" on allowlist policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn allowlist_remove_destination_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    destination: &[u8; 32],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Block destination ")?;
    w.write_hex_lower(destination)?;
    w.write_str(" on allowlist policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn allowlist_pause_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Pause allowlist policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn allowlist_resume_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Resume allowlist policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

// ── Phase 2: velocity-guard admin (3) ────────────────────────────

pub fn velocity_update_window_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    max_sigs_per_window: u32,
    window_slots: u64,
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Update velocity window on policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    w.write_str(" to ")?;
    w.write_u32_dec(max_sigs_per_window)?;
    w.write_str(" signatures per ")?;
    w.write_u64_dec(window_slots)?;
    w.write_str(" slots")?;
    Ok(w.len())
}

pub fn velocity_pause_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Pause velocity-guard policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn velocity_resume_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Resume velocity-guard policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

// ── Phase 2: time-lock admin (3) ─────────────────────────────────

pub fn time_lock_mode_label(mode: u8) -> &'static str {
    match mode {
        0 => "before",
        1 => "after",
        2 => "between",
        3 => "recurring",
        _ => "unknown",
    }
}

pub fn time_lock_update_window_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    mode: u8,
    start_slot: u64,
    end_slot: u64,
    recurring_period_slots: u64,
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Update time-lock window on policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    w.write_str(" mode ")?;
    w.write_str(time_lock_mode_label(mode))?;
    w.write_str(" start ")?;
    w.write_u64_dec(start_slot)?;
    w.write_str(" end ")?;
    w.write_u64_dec(end_slot)?;
    w.write_str(" period ")?;
    w.write_u64_dec(recurring_period_slots)?;
    Ok(w.len())
}

pub fn time_lock_pause_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Pause time-lock policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn time_lock_resume_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Resume time-lock policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

// ── Phase 2: oracle-conditional admin (3) ────────────────────────

pub fn oracle_update_bounds_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    min_price: i64,
    max_price: i64,
    max_age_slots: u64,
    max_confidence_bps: u16,
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Update oracle bounds on policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    w.write_str(" min ")?;
    w.write_i64_dec(min_price)?;
    w.write_str(" max ")?;
    w.write_i64_dec(max_price)?;
    w.write_str(" maxAge ")?;
    w.write_u64_dec(max_age_slots)?;
    w.write_str(" maxConfidence ")?;
    w.write_u16_dec(max_confidence_bps)?;
    w.write_str(" bps")?;
    Ok(w.len())
}

pub fn oracle_pause_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Pause oracle-conditional policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn oracle_resume_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Resume oracle-conditional policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

// ── Phase 2: passkey-step-up admin (3) ───────────────────────────

pub fn passkey_update_policy_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    threshold_amount: u64,
    passkey_pubkey: &[u8; 33],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Update passkey step-up on policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    w.write_str(" threshold ")?;
    w.write_u64_dec(threshold_amount)?;
    w.write_str(" passkey ")?;
    w.write_hex_lower(passkey_pubkey)?;
    Ok(w.len())
}

pub fn passkey_pause_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Pause passkey step-up policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn passkey_resume_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Resume passkey step-up policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

// ── Phase 2: session-keys admin (4) ──────────────────────────────

pub fn session_keys_revoke_session_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Revoke session keys on policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn session_keys_add_allowed_program_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    program_id: &Address,
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Allow program ")?;
    w.write_base58_32(program_id.as_array())?;
    w.write_str(" on session-keys policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn session_keys_remove_allowed_program_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    program_id: &Address,
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Block program ")?;
    w.write_base58_32(program_id.as_array())?;
    w.write_str(" on session-keys policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn session_keys_close_session_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    recipient: &Address,
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Close session-keys policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    w.write_str(" refund recipient ")?;
    w.write_base58_32(recipient.as_array())?;
    Ok(w.len())
}

// ── Phase 2: fhe-gated admin (3) ─────────────────────────────────

pub fn fhe_rotate_authority_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    new_fhe_authority: &Address,
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Rotate FHE authority on policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    w.write_str(" to ")?;
    w.write_base58_32(new_fhe_authority.as_array())?;
    Ok(w.len())
}

pub fn fhe_pause_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Pause fhe-gated policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}

pub fn fhe_resume_message(
    out: &mut [u8; MAX_HUMAN_MESSAGE_BYTES],
    policy: &Address,
    dwallet: &Address,
) -> Result<usize, HumanMessageError> {
    let mut w = MsgWriter::new(out);
    w.write_str("Resume fhe-gated policy ")?;
    w.write_base58_32(policy.as_array())?;
    w.write_str(" for dWallet ")?;
    w.write_base58_32(dwallet.as_array())?;
    Ok(w.len())
}
