package openapi

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"
)

// The committed gateway/openapi.yaml is a DERIVATIVE of this package — it must
// stay byte-identical to SnapshotYAML(). The runtime `/openapi.json` is the
// live source of truth; the YAML snapshot exists for consumers (SDK generators,
// docs) that expect a versioned file in the repo. A guard test
// (TestSnapshotYAMLInSync) fails if the file drifts, so the snapshot can never
// silently go stale again.
//
// Regenerate after changing routes.All or anything in this package:
//
//	cd gateway && go run ./cmd/openapi-gen
const (
	// SnapshotServiceName / SnapshotServiceVersion mirror the runtime config in
	// internal/api/openapi.go so the static file matches what the deployment
	// serves at /openapi.json.
	SnapshotServiceName    = "andromeda-gateway"
	SnapshotServiceVersion = "0.1.0"
	// SnapshotBaseURL pins the production server block. Deterministic so the
	// guard test never depends on per-environment config.
	SnapshotBaseURL = "https://andromeda-gateway-production.up.railway.app"
)

const snapshotHeader = `# Code generated by cmd/openapi-gen; DO NOT EDIT.
#
# This file mirrors the runtime /openapi.json (assembled from routes.All +
# internal/openapi). The live spec at /openapi.json is canonical; this snapshot
# is here for SDK generators and docs that want a versioned file.
#
# Regenerate after changing routes or the generator:
#     cd gateway && go run ./cmd/openapi-gen
#
# A guard test (internal/openapi TestSnapshotYAMLInSync) fails if this drifts.
`

// SnapshotYAML renders the canonical OpenAPI 3.1 document as YAML, prefixed
// with the generated-file header. The cmd/openapi-gen tool writes the result to
// gateway/openapi.yaml; the guard test compares the committed file against it.
func SnapshotYAML() ([]byte, error) {
	gen := Generator{
		ServiceName:    SnapshotServiceName,
		ServiceVersion: SnapshotServiceVersion,
		BaseURL:        SnapshotBaseURL,
	}
	body, err := yaml.Marshal(gen.Build())
	if err != nil {
		return nil, fmt.Errorf("marshal openapi document: %w", err)
	}
	var buf bytes.Buffer
	buf.WriteString(snapshotHeader)
	buf.Write(body)
	return buf.Bytes(), nil
}
